-- AlterTable
ALTER TABLE "students" ADD COLUMN     "locale" TEXT DEFAULT 'pt_BR',
ADD COLUMN     "mouse_icon_scale" DOUBLE PRECISION DEFAULT 0.2,
ALTER COLUMN "save_volume" SET DEFAULT 100.0,
ALTER COLUMN "save_volume" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "save_volume_music" SET DEFAULT 100.0,
ALTER COLUMN "save_volume_music" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "save_volume_sfx" SET DEFAULT 100.0,
ALTER COLUMN "save_volume_sfx" SET DATA TYPE DOUBLE PRECISION;
